---
- name: provision spine 1
  hosts: server1, server2
  become: true
#  connection: local
  gather_facts: no
  tasks:
  - name: Copy over interfaces
    copy: src=./flatfiles/{{inventory_hostname}}/interfaces dest=/etc/network/interfaces
    notify: reload networking

  handlers:
  - name: reload networking
    shell: sudo service networking restart

